import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const root=path.resolve(path.dirname(new URL(import.meta.url).pathname));
const serverFile=path.join(root,'server.mjs');
const port=8899;
const appRoot=path.dirname(root);
const activeFiles=['app.js','index.html','styles.css','manifest.webmanifest','sw.js','data/knowledge.json','data/source-registry.json','data/update-manifest.example.json','backend/data/manifest.json'];
const appSourceStatic=fs.readFileSync(path.join(appRoot,'app.js'),'utf8');
const appVersionStatic=appSourceStatic.match(/const APP_VERSION='([^']+)'/)?.[1];
assert.ok(appVersionStatic,'APP_VERSION must exist before server tests');
const minor=appVersionStatic.split('.')[1];
const expectedMinor=`V${minor}`;
assert.match(appVersionStatic,/^\d+\.\d+\.\d+$/);
for(const rel of activeFiles){
  const file=path.join(appRoot,rel); assert.ok(fs.existsSync(file),`active release file missing: ${rel}`);
  const body=fs.readFileSync(file,'utf8');
  assert.equal(body.includes(`0.${Number(minor)-1}.0`),false,`stale previous app version found in active file: ${rel}`);
  assert.equal(body.includes(`V${Number(minor)-1} · release candidate`),false,`stale release marker found in active file: ${rel}`);
}
const currentReleaseDoc=`docs/RELEASE-CANDIDATE-V${minor}.md`; assert.ok(fs.existsSync(path.join(appRoot,currentReleaseDoc)),`current release document missing: ${currentReleaseDoc}`);
const readme=fs.readFileSync(path.join(appRoot,'README.md'),'utf8');
const currentReadme=readme.split(/^## /m).find(x=>x.startsWith(`V${minor} —`))||'';
assert.ok(currentReadme, 'README current release section must exist');
assert.equal(currentReadme.includes(`0.${Number(minor)-1}.0`),false,'README current release section contains stale app version');
assert.ok(currentReadme.includes(`0.${minor}.0`),'README current release must contain current app version');
const swSource=fs.readFileSync(path.join(appRoot,'sw.js'),'utf8');
const shellMatch=swSource.match(/const APP_SHELL = \[(.*?)\];/s); assert.ok(shellMatch,'service worker App Shell must be declared');
const shellItems=[...shellMatch[1].matchAll(/['"](\.\/[^'"]+)['"]/g)].map(m=>m[1]);
assert.ok(shellItems.length>=6,'service worker App Shell unexpectedly small');
for(const item of shellItems){assert.ok(fs.existsSync(path.join(appRoot,item.replace(/^\.\//,''))),`service worker shell resource missing: ${item}`);}
assert.match(swSource,/req\.mode==='navigate'/,'service worker must use a navigation-aware strategy');
assert.match(swSource,/fetch\(req\)\.then\(response=>/,'service worker must attempt network for navigation');
assert.match(appSourceStatic,/register\('\.\/sw\.js',\{updateViaCache:'none'\}\)/,'service worker registration must disable HTTP cache for update checks');
const html=fs.readFileSync(path.join(appRoot,'index.html'),'utf8');
assert.doesNotMatch(html,/\son[a-z]+\s*=\s*["']/i,'inline event handlers are forbidden');
assert.doesNotMatch(html,/unsafe-inline/,'unsafe-inline must not be present in active HTML');
const css=fs.readFileSync(path.join(appRoot,'styles.css'),'utf8');
for(const token of ['--black:','--rose:','--gold:','--silver:','--cream:']) assert.match(css,new RegExp(token.replace(':','\\:')),'brand palette variable missing: '+token);
assert.doesNotMatch(css,/style-src[^;]*unsafe-inline/,'CSS policy must not reintroduce unsafe-inline');
const logoSvg=fs.readFileSync(path.join(appRoot,'assets','logo.svg'),'utf8');
assert.ok(logoSvg.includes('#c9a15b')||logoSvg.includes('#e1c58e'),'logo must retain a gold brand accent');
assert.ok(logoSvg.includes('DESINZI'),'logo must contain the DESINZI wordmark');
assert.doesNotMatch(logoSvg,/magnifying|lupa/i,'approved logo must not add a magnifying glass');
for(const [name,value] of [['black','#0d0d0f'],['rose','#d7a09a'],['gold','#c9a15b'],['silver','#bfc3c7'],['cream','#f5efe8']]) assert.match(css,new RegExp(`--${name}:${value.replace('#','\\#')}`),`brand color mismatch: ${name}`);
for(const id of ['legal','privacy','ip','updates','qa','settings']) assert.ok(html.includes(`id=\"${id}\"`),`required screen missing: ${id}`);
assert.ok(fs.existsSync(path.join(appRoot,'assets','logo.png')),'PWA PNG icon missing');
assert.ok(fs.existsSync(path.join(appRoot,'assets','logo.svg')),'SVG logo missing');
const embeddedKey=appSourceStatic.match(/UPDATE_SIGNING_PUBLIC_KEY_SPKI_B64='([^']+)'/)?.[1]; assert.ok(embeddedKey,'embedded update signing public key missing');
for(const f of ['.env.example','../.gitignore']) { const fp=path.resolve(root,f); assert.ok(fs.existsSync(fp),`security/config file missing: ${f}`); }
assert.doesNotMatch(appSourceStatic,/ADMIN_TOKEN\s*=|Bearer\s+[A-Za-z0-9_-]{12,}/,'secrets must not be hard-coded in frontend');
assert.ok(fs.existsSync(path.join(root,'Dockerfile')),'production backend Dockerfile missing');
assert.ok(fs.existsSync(path.join(appRoot,'docs','PRODUCTION-RUNBOOK-V55.md')),'production runbook missing');
assert.doesNotMatch(fs.readFileSync(path.join(appRoot,'index.html'),'utf8'),/Desinzero|DESINZERO/,'obsolete product name must not appear in active UI');
const knowledgeSources=JSON.parse(fs.readFileSync(path.join(appRoot,'data','knowledge.json'),'utf8')).sources||[];
const registrySources=JSON.parse(fs.readFileSync(path.join(appRoot,'data','source-registry.json'),'utf8')).sources||[];
const backendSources=JSON.parse(fs.readFileSync(path.join(root,'data','sources.json'),'utf8'));
assert.deepEqual(registrySources.map(x=>x.id).sort(),knowledgeSources.map(x=>x.id).sort(),'source registry must exactly match knowledge source IDs'); assert.deepEqual(backendSources.map(x=>x.id).sort(),knowledgeSources.map(x=>x.id).sort(),'backend source registry must exactly match knowledge source IDs'); for(const src of knowledgeSources){ assert.ok(registrySources.some(x=>x.id===src.id),`source registry missing: ${src.id}`); assert.ok(backendSources.some(x=>x.id===src.id),`backend source registry missing: ${src.id}`); }
const updateExample=JSON.parse(fs.readFileSync(path.join(appRoot,'data','update-manifest.example.json'),'utf8'));
assert.deepEqual([...updateExample.sources].sort(),knowledgeSources.map(x=>x.id).sort(),'update manifest source list must match knowledge source list');
const dockerfile=fs.readFileSync(path.join(root,'Dockerfile'),'utf8');
assert.match(dockerfile,/USER node/,'backend container must not run as root');
assert.match(dockerfile,/node:24-alpine/,'backend container base image must be explicit');
const pwa=JSON.parse(fs.readFileSync(path.join(appRoot,'manifest.webmanifest'),'utf8'));
assert.equal(pwa.name,'DESINZI · ZERO HUMO');
assert.equal(pwa.scope,'./');
assert.equal(pwa.start_url,'./');
assert.equal(pwa.background_color,'#0d0d0f');
assert.equal(pwa.theme_color,'#0d0d0f');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'desinzi-qa-'));
fs.cpSync(path.join(root,'data'),path.join(tmp,'data'),{recursive:true});
const child=spawn(process.execPath,[serverFile],{cwd:root,env:{...process.env,PORT:String(port),ADMIN_TOKEN:'qa-secret',DATA_DIR:path.join(tmp,'data')},stdio:['ignore','pipe','pipe']});
const wait=new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('server timeout')),5000);child.stdout.on('data',d=>{if(String(d).includes('listening')){clearTimeout(t);resolve();}});child.on('error',reject);});
try {
  await wait;
  const base=`http://127.0.0.1:${port}`;
  // El contrato canónico interno es /v1/. Las rutas externas de proveedores (p.ej. Open Beauty Facts /api/v3) son independientes.
  const frontendRoutes=fs.readFileSync(path.join(root,'../app.js'),'utf8'); const backendRoutes=fs.readFileSync(path.join(root,'server.mjs'),'utf8');
  assert.doesNotMatch(frontendRoutes,/fetchJSON\(['"]\/api\//,'frontend must not call a local /api/ route');
  assert.doesNotMatch(backendRoutes,/u\.pathname===['"]\/api\//,'backend must not expose a local /api/ route');
  const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
  assert.equal(pkg.version,'1.0.0');
  const apiContract=fs.readFileSync(path.join(path.dirname(root),'docs','API-CONTRACT-V55.md'),'utf8');
  for(const route of ['/v1/health','/v1/knowledge/manifest','/v1/knowledge/payload.json','/v1/knowledge/status','/v1/sources','/v1/admin/pending','/v1/admin/change','/v1/admin/change/{id}/review']) assert.ok(apiContract.includes(route),`API contract missing route: ${route}`);
  for(const route of ['/v1/health','/v1/knowledge/manifest','/v1/knowledge/payload.json','/v1/knowledge/status','/v1/sources']) assert.ok(backendRoutes.includes(route),`backend route missing from implementation: ${route}`);
  const appSource=fs.readFileSync(path.join(path.dirname(root),'app.js'),'utf8');
  const appVersion=appSource.match(/const APP_VERSION='([^']+)'/)?.[1];
  assert.ok(appVersion,'app version must be declared exactly once');
  assert.match(appVersion,/^\d+\.\d+\.\d+$/);
  const dataVersion=appSource.match(/const DATA_VERSION='([^']+)'/)?.[1];
  assert.ok(dataVersion?.includes(`V${appVersion.split('.')[1]}`),'DATA_VERSION must identify the current app release');
  const appVersionMatches=appSource.match(/const APP_VERSION=/g)||[];
  assert.equal(appVersionMatches.length,1,'APP_VERSION must have a single declaration');
  const sw=fs.readFileSync(path.join(path.dirname(root),'sw.js'),'utf8');
  assert.equal(sw.match(/const CACHE_NAME = '([^']+)'/)?.[1],`desinzi-zero-humo-app-v${appVersion.split('.')[1]}`,'PWA cache must follow app minor version');
  assert.match(appSource,/scheduleKnowledgeUpdateCheck/,'automatic knowledge update scheduler must exist'); assert.match(appSource,/window\.isSecureContext/,'camera flow must guard insecure production contexts');
  const readme=fs.readFileSync(path.join(path.dirname(root),'README.md'),'utf8');
  assert.ok(readme.startsWith(`## V${appVersion.split('.')[1]} — Release Candidate técnico`),'README current release must match app version');
  const releaseDoc=fs.readFileSync(path.join(path.dirname(root),'docs',`RELEASE-CANDIDATE-V${appVersion.split('.')[1]}.md`),'utf8');
  assert.match(releaseDoc,new RegExp('App: `'+appVersion.replaceAll('.','\\.')+'`'));
  const bundled=JSON.parse(fs.readFileSync(path.join(path.dirname(root),'data','knowledge.json'),'utf8'));
  assert.equal(bundled.knowledgeVersion,'2026.10.04-016');
  assert.equal(bundled.schemaVersion,4);
  let r=await fetch(base+'/v1/health'); assert.equal(r.status,200); const health=await r.json(); assert.equal(health.ok,true); assert.equal(health.version,'1.0.0');
  r=await fetch(base+'/v1/health',{headers:{Origin:'https://allowed.example'}}); assert.equal(r.status,200); assert.equal(r.headers.get('access-control-allow-origin'),null,'unconfigured origins must not receive CORS access');
  r=await fetch(base+'/v1/knowledge/manifest'); assert.equal(r.status,200); const manifest=await r.json(); assert.ok(manifest.version); const manifestRaw=fs.readFileSync(path.join(tmp,'data','manifest.json'),'utf8'); const manifestObj=JSON.parse(manifestRaw); assert.equal(manifestObj.signatureAlgorithm,'ECDSA-P256-SHA256'); assert.equal(manifestObj.signingKeyId,'desinzi-update-2026'); const payloadRawForSig=fs.readFileSync(path.join(tmp,'data','payload.json')); const pub=crypto.createPublicKey({key:Buffer.from(manifestObj.publicKeySpkiBase64,'base64'),format:'der',type:'spki'}); assert.equal(crypto.verify('sha256',payloadRawForSig,{key:pub,dsaEncoding:'ieee-p1363'},Buffer.from(manifestObj.signature,'base64')),true,'knowledge signature must verify'); assert.equal(manifest.schemaVersion,4); assert.equal(manifest.minAppVersion,appVersion); assert.equal(manifest.version,'2026.10.04-016'); assert.equal(manifest.schemaVersion,4); assert.equal(manifest.publicKeySpkiBase64,embeddedKey,'manifest public key must match app trust anchor');
  r=await fetch(base+'/v1/knowledge/payload.json'); assert.equal(r.status,200); const payload=await r.json(); assert.equal(payload.knowledgeVersion,manifest.version); assert.equal(payload.schemaVersion,4); assert.ok(payload.ingredients.glycerin); assert.ok(payload.ingredients['hc red no 18']); assert.ok(payload.regulatoryRules['hc-red-no-18']); assert.ok(payload.regulatoryRules['aluminium-containing-ingredients']); assert.ok(payload.regulatoryRules['hexyl-salicylate']); assert.ok(payload.regulatoryRules['o-phenylphenol']); assert.ok(payload.sources.some(x=>x.id==='eu-reg-2026-78-corrigendum')); assert.ok(payload.sources.some(x=>x.id==='sccs-opinions-2026')); assert.ok(payload.sources.some(x=>x.id==='sccs-mandates-2026')); assert.ok(Array.isArray(payload.scientificMonitoring?.records)); assert.ok(payload.scientificMonitoring.records.some(x=>x.status==='opinion-final')); assert.ok(payload.scientificMonitoring.records.some(x=>x.status==='mandate')); assert.ok(payload.scientificMonitoring.records.some(x=>x.substance==='Cyclamen Aldehyde')); assert.ok(payload.scientificMonitoring.records.some(x=>x.substance==='Glyoxylic Acid')); assert.ok(payload.scientificMonitoring.records.some(x=>x.substance==='Basic Brown 16')); assert.ok(payload.scientificMonitoring.records.some(x=>x.substance==='Thiomersal and Phenylmercuric salts')); assert.ok(Array.isArray(payload.regulatoryMonitoring?.records)); assert.equal(payload.regulatoryMonitoring.records[0].legalStatus,'not-in-force'); assert.equal(payload.knowledgeVersion,'2026.10.04-016'); assert.equal(payload.ocrCorrectionPolicy.enabled,true); assert.equal(payload.ocrCorrectionPolicy.maxEditDistance,1); assert.equal(payload.ocrCorrectionPolicy.minScore,0.87); assert.equal(manifest.signatureAlgorithm,'ECDSA-P256-SHA256'); assert.equal(manifest.signingKeyId,'desinzi-update-2026'); assert.ok(manifest.signature); assert.ok(manifest.publicKeySpkiBase64);
  r=await fetch(base+'/v1/knowledge/status'); assert.equal(r.status,200); let status=await r.json(); assert.equal(status.integrityOk,true); assert.equal(status.schemaOk,true);
  const payloadPath=path.join(tmp,'data','payload.json'); const goodRaw=fs.readFileSync(payloadPath,'utf8'); fs.writeFileSync(payloadPath,goodRaw.trim().slice(0,-1)+',"qaTamper":true}\n','utf8');
  r=await fetch(base+'/v1/knowledge/status'); assert.equal(r.status,200); status=await r.json(); assert.equal(status.integrityOk,false,'tampered payload must fail integrity'); fs.writeFileSync(payloadPath,goodRaw,'utf8'); const originalManifest=JSON.parse(fs.readFileSync(path.join(tmp,'data','manifest.json'),'utf8')); fs.writeFileSync(payloadPath,goodRaw.replace('2026.10.04-016','2026.10.04-016-tampered'),'utf8'); const tamperedRaw=fs.readFileSync(payloadPath); assert.equal(crypto.verify('sha256',tamperedRaw,{key:pub,dsaEncoding:'ieee-p1363'},Buffer.from(originalManifest.signature,'base64')),false,'tampered payload must fail signature verification'); fs.writeFileSync(payloadPath,goodRaw,'utf8');
  r=await fetch(base+'/v1/knowledge/status'); status=await r.json(); assert.equal(status.integrityOk,true,'restored payload must pass integrity');
  r=await fetch(base+'/v1/admin/pending'); assert.equal(r.status,401);
  r=await fetch(base+'/v1/admin/pending',{headers:{Authorization:'Bearer wrong'}}); assert.equal(r.status,401);
  r=await fetch(base+'/v1/admin/pending',{headers:{Authorization:'Bearer qa'}}); assert.equal(r.status,401,'mismatched token length must fail safely');
  r=await fetch(base+'/v1/admin/change',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer qa-secret'},body:JSON.stringify({title:'QA change',kind:'test',summary:'Automated QA',sources:[]})});
  assert.equal(r.status,201); const change=await r.json(); assert.equal(change.status,'pending_review');
  r=await fetch(base+`/v1/admin/change/${change.id}/review`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer qa-secret'},body:JSON.stringify({decision:'approved',note:'QA'})});
  assert.equal(r.status,200); assert.equal((await r.json()).status,'approved');
  const log=fs.readFileSync(path.join(tmp,'data','audit.log'),'utf8');
  assert.ok(!log.includes('127.0.0.1')&&!log.includes('ipHash'), 'audit must not store network identifiers');
  console.log(`QA OK: V${appVersion.split('.')[1]} final release coherence, brand palette, app/data/PWA version coherence, scientific-monitoring/regulatory-monitoring, schema/OCR policy, current-source registry, product comparison/cross-check contract, SHA-256 tamper detection, auth, review workflow and audit minimization`);
} finally { child.kill('SIGTERM'); }
